ASP/Models/SongViewModel.cs
namespace PresentationLayer.Models
{
    public class SongViewModel
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public int Length { get; set; }


        public SongViewModel(int ID, string Name, int Length)
        {
            this.ID = ID;
            this.Name = Name;
            this.Length = Length;
        }

        public SongViewModel()
        {
            
        }
    }
}

ASP/Controllers/SongController.cs
using Microsoft.AspNetCore.Mvc;
using PresentationLayer.Models;
using LogicLayer;
using DataAccessLayer;

namespace PresentationLayer.Controllers
{
    public class SongController : Controller
    {
        private readonly IArtistContainer artistContainer;
        private readonly ISongContainer songContainer;

        public SongController(IArtistContainer artistContainer, ISongContainer songContainer)
        {
            this.artistContainer = artistContainer;
            this.songContainer = songContainer;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult PlayMusic()
        {
            return View();
        }

        public IActionResult AddMusic()
        {
            return View();
        }

        public IActionResult ListMusic()
        {
            List<Song> songs = songContainer.GetSongs();
            List<SongViewModel> musicVMs = new List<SongViewModel>();

            foreach(Song s in songs)
            {
                musicVMs.Add(new SongViewModel(s.ID, s.Name, s.Length));
            }

            return View(musicVMs);
        }

        public IActionResult ListArtistsBySong(int songId)
        {
            List<ArtistViewModel> artistVMs = new List<ArtistViewModel>();

            
            foreach(Artist a in songContainer.GetArtistsBySong(songId))
            {
                artistVMs.Add(new ArtistViewModel(a.ID, a.Name, a.Age));
            }

            Song s = songContainer.GetSongByID(songId);
            SongViewModel songVM = new SongViewModel(s.ID, s.Name, s.Length);

            ArtistsSongViewModel artistsSongVM = new ArtistsSongViewModel(artistVMs, songVM);

            return View(artistsSongVM);
        }

        public IActionResult EditMusic(List<int> ids)
        {
            List<SongViewModel> musicVMs = new List<SongViewModel>();
            foreach (int id in ids)
            {
                Song song = songContainer.GetSongByID(id);
                musicVMs.Add(new SongViewModel(song.ID, song.Name, song.Length));
            }

            return View(musicVMs);
        }

        [HttpPost]
        public IActionResult EditMusic(SongViewModel musicVM)
        {
            Song song = new Song(musicVM.ID, musicVM.Name, musicVM.Length);
            songContainer.UpdateSong(song);
            return RedirectToAction("ListMusic");
        }

        [HttpPost]
        public IActionResult AddMusic(SongViewModel musicVM)
        {
            Song song = new Song(musicVM.Name, musicVM.Length);
            songContainer.InsertSong(song);
            ViewBag.Music = musicVM;
            return RedirectToAction("AddMusic");
        }

        [HttpPost]
        public IActionResult Delete(int id)
        {
            songContainer.DeleteSongByID(id);
            return Ok(id);
        }

        public IActionResult LinkArtistToSong()
        {
            List<Artist> artists = artistContainer.LoadArtist();
            List<Song> songs = songContainer.GetSongs();
            ArtistsSongsViewModel artistsSongsVM = new ArtistsSongsViewModel(artists[0].ID, artists, songs[0].ID, songs);

            return View(artistsSongsVM);
        }

        [HttpPost]
        public IActionResult LinkArtistToSong(ArtistsSongsViewModel artistSongsVM)
        {
            songContainer.LinkSongToArtist(artistSongsVM.SelectedSongID, artistContainer.FindArtistByID(artistSongsVM.SelectedArtistID));
            return RedirectToAction("ListArtistsbySong", new { songId = artistSongsVM.SelectedSongID });
        }
    }
}

ASP/Views/Song/AddMusic.cshtml
@model SongViewModel

@{
    ViewData["Title"] = "AddMusic";
}
<div class="text-center">

    <h1>AddMusic</h1>
    <form method=POST asp-controller=Song asp-action=AddMusic>
    <br />
    <br />
        <p1>Name</p1>
            <input asp-for="Name" type="text" />
        <p1>Length</p1>
            <input asp-for="Length" type="text"/>
            <br />
            <br />
        <button type="submit" class="btn btn-primary">Muziek Toevoegen</button>
        
    </form>
</div>

ASP/Views/Song/EditMusic.cshtml
@{
    ViewData["Title"] = "EditMusic";
}

@model List<PresentationLayer.Models.SongViewModel>

<h1>EditMusic</h1>
 
@if(Model.Count < 1)
{
    <label style="font-style:italic">Er zijn geen producten gevonden...</label>
}

<form method="post" asp-controller="Song">
    <table class="table table-striped">
    <thead class="thead-dark">
        <tr>            
            <th scope="col">ID</th>
            <th scope="col">Name</th>
            <th scope="col">Length</th>
            <th scope="col"></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <partial id="partialview" name="MusicRowEdit" model="@item" />
        }
    </tbody>
    </table>

</form>

ASP/Views/Song/LinkArtistToSong.cshtml
@model ArtistsSongsViewModel

<div class="text-center">
    <h1>Link Artist To Song</h1>
    <form asp-controller=Song asp-action=LinkArtistToSong method="post">
    <br />
    <br />
        <p1>Artist</p1>
            <input type="hidden" asp-for="Artists" />
            <select asp-for="SelectedArtistID" asp-items="@(new SelectList(Model.Artists, "ID", "Name"))"></select>
        <p1>Song</p1>
            <input type="hidden" asp-for="Songs" />
            <select asp-for="SelectedSongID" asp-items="@(new SelectList(Model.Songs, "ID", "Name"))"></select>
            <br />
            <br />
        <button type="submit" class="btn btn-primary">Koppelen</button>
        
    </form>
</div>

ASP/Views/Song/ListArtistsBySong.cshtml
@model ArtistsSongViewModel
@if (Model == null) return;

<h1>Song: @Model.Song.Name</h1>
<p>Lengte: @Model.Song.Length</p>

@if(Model.Artists == null || Model.Artists.Count < 1)
{
    <label style="font-style:italic">Er zijn geen artiesten gevonden...</label>
} else {
    <p>Artiesten:</p>
    <table class="table table-striped">
    <thead class="thead-dark">
        <tr>
            <th scope="col">ID</th>
            <th scope="col">Name</th>
            <th scope="col">Length</th>
            <th scope="col"></th>
        </tr>
    </thead>
        <tbody>
            @if (Model.Artists != null)
            {
                @foreach (var item in Model.Artists)
                {
                    <partial id="partialview" name="ArtistRow" model="@item" />
                }
            }
        </tbody>
    </table>
}

ASP/Views/Song/ListMusic.cshtml
@{
    ViewData["Title"] = "ListMusic";
}

@model List<PresentationLayer.Models.SongViewModel>

<h1>ListMusic</h1>
 
@if(Model.Count < 1)
{
    <label style="font-style:italic">Er zijn geen producten gevonden...</label>
}

<table class="table table-striped">
<thead class="thead-dark">
    <tr>
        <th class="checkbox_column" scope="col"></th>
        <th scope="col">ID</th>
        <th scope="col">Name</th>
        <th scope="col">Length</th>
        <th scope="col"></th>
    </tr>
</thead>
<tbody>
    @foreach (var item in Model)
    {
        <partial id="partialview" name="MusicRowSelect" model="@item" />
    }
</tbody>
</table>

<input type="button" value="Aantal wijzigen" id="EditButton" />
<input type="button" value="Verwijderen" id="DeleteButton"/>

ASP/Views/Song/PlayMusic.cshtml
@{
    ViewData["Title"] = "PlayMusic";
}

<div class="text-center">
    <h1>PlayMusic</h1>
        <input type="text" itemid="musicsearch" name="musicsearch"><br/>
        <input type="submit" class="btn btn-primary" value="Search"><br/>
        <input type="button" class="btn btn-primary" value="Play" onclick="window.open='https://soundcloud.com/pushat/pusha-t-neck-wrist-feat-jay-z?in=pushat/sets/its-almost-dry-1'">
        <input type="button" class="btn btn-primary" value="Pause">
        <input type="button" class="btn btn-primary" value="Skip">
        <input type="button" class="btn btn-primary" value="Repeat">
</div>