ASP/Controllers/ArtistController.cs
using Microsoft.AspNetCore.Mvc;
using LogicLayer;
using DataAccessLayer;
using PresentationLayer.Models;

namespace PresentationLayer.Controllers
{
    public class ArtistController : Controller
    {
        private readonly IArtistContainer artistContainer;

        public ArtistController(IArtistContainer artistContainer)
        {
            this.artistContainer = artistContainer;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult AddArtist()
        {
            return View();
        }

        public IActionResult ListArtist()
        {
            List<ArtistViewModel> artists = new List<ArtistViewModel>();

            foreach(Artist artist in artistContainer.LoadArtist()) {
                artists.Add(new ArtistViewModel(artist.ID, artist.Name, artist.Age));
            }

            return View(artists);
        }

        [HttpPost]
        public IActionResult AddArtist(ArtistViewModel artistViewModel)
        {
            Artist artist = new Artist(artistViewModel.Name, artistViewModel.Age);
            artistContainer.InsertArtist(artist);
            ViewBag.Music = artistViewModel;
            return RedirectToAction("AddArtist");
        }

        public IActionResult ListSongsByArtist(int artistId)
        {
            List<SongViewModel> songs = new List<SongViewModel>();

            foreach (Song song in artistContainer.GetSongsByArtist(artistId))
            {
                songs.Add(new SongViewModel(song.ID, song.Name, song.Length));
            }
            Artist artist = artistContainer.FindArtistByID(artistId);
            ArtistViewModel artistVM = new ArtistViewModel(artist.ID, artist.Name, artist.Age);

            SongsArtistViewModel songsArtistViewModel = new SongsArtistViewModel(songs, artistVM);
            return View(songsArtistViewModel);
        }


        [HttpPost]
        public IActionResult UnlinkSongFromArtist(int artistId, int songId)
        {
            artistContainer.UnlinkArtistFromSong(artistId, songId);
            return RedirectToAction("ListArtistsbySong", "Song", new { songId = songId });
        }
    }
}

ASP/Controllers/SongController.cs
using Microsoft.AspNetCore.Mvc;
using PresentationLayer.Models;
using LogicLayer;
using DataAccessLayer;

namespace PresentationLayer.Controllers
{
    public class SongController : Controller
    {
        private readonly IArtistContainer artistContainer;
        private readonly ISongContainer songContainer;

        public SongController(IArtistContainer artistContainer, ISongContainer songContainer)
        {
            this.artistContainer = artistContainer;
            this.songContainer = songContainer;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult PlayMusic()
        {
            return View();
        }

        public IActionResult AddMusic()
        {
            return View();
        }

        public IActionResult ListMusic()
        {
            List<Song> songs = songContainer.GetSongs();
            List<SongViewModel> musicVMs = new List<SongViewModel>();

            foreach(Song s in songs)
            {
                musicVMs.Add(new SongViewModel(s.ID, s.Name, s.Length));
            }

            return View(musicVMs);
        }

        public IActionResult ListArtistsBySong(int songId)
        {
            List<ArtistViewModel> artistVMs = new List<ArtistViewModel>();

            
            foreach(Artist a in songContainer.GetArtistsBySong(songId))
            {
                artistVMs.Add(new ArtistViewModel(a.ID, a.Name, a.Age));
            }

            Song s = songContainer.GetSongByID(songId);
            SongViewModel songVM = new SongViewModel(s.ID, s.Name, s.Length);

            ArtistsSongViewModel artistsSongVM = new ArtistsSongViewModel(artistVMs, songVM);

            return View(artistsSongVM);
        }

        public IActionResult EditMusic(List<int> ids)
        {
            List<SongViewModel> musicVMs = new List<SongViewModel>();
            foreach (int id in ids)
            {
                Song song = songContainer.GetSongByID(id);
                musicVMs.Add(new SongViewModel(song.ID, song.Name, song.Length));
            }

            return View(musicVMs);
        }

        [HttpPost]
        public IActionResult EditMusic(SongViewModel musicVM)
        {
            Song song = new Song(musicVM.ID, musicVM.Name, musicVM.Length);
            songContainer.UpdateSong(song);
            return RedirectToAction("ListMusic");
        }

        [HttpPost]
        public IActionResult AddMusic(SongViewModel musicVM)
        {
            Song song = new Song(musicVM.Name, musicVM.Length);
            songContainer.InsertSong(song);
            ViewBag.Music = musicVM;
            return RedirectToAction("AddMusic");
        }

        [HttpPost]
        public IActionResult Delete(int id)
        {
            songContainer.DeleteSongByID(id);
            return Ok(id);
        }

        public IActionResult LinkArtistToSong()
        {
            List<Artist> artists = artistContainer.LoadArtist();
            List<Song> songs = songContainer.GetSongs();
            ArtistsSongsViewModel artistsSongsVM = new ArtistsSongsViewModel(artists[0].ID, artists, songs[0].ID, songs);

            return View(artistsSongsVM);
        }

        [HttpPost]
        public IActionResult LinkArtistToSong(ArtistsSongsViewModel artistSongsVM)
        {
            songContainer.LinkSongToArtist(artistSongsVM.SelectedSongID, artistContainer.FindArtistByID(artistSongsVM.SelectedArtistID));
            return RedirectToAction("ListArtistsbySong", new { songId = artistSongsVM.SelectedSongID });
        }
    }
}

ASP/Views/Shared/ArtistRow.cshtml
@model PresentationLayer.Models.ArtistViewModel
<tr>
    <td>@Model.ID</td>
    <td>@Model.Name</td>
    <td>@Model.Age</td>
    <td scope="row">
        <a asp-controller="Artist" asp-action="ListSongsByArtist" asp-route-artistId=@Model.ID><button>Check Songs</button></a>
    </td>
</tr>

ASP/Views/Shared/MusicRow.cshtml
@model PresentationLayer.Models.SongViewModel
<tr>
    <td>@Model.ID</td>
    <td>@Model.Name</td>
    <td>@Model.Length</td>
</tr>

ASP/Views/Shared/MusicRowByArtist.cshtml
@model PresentationLayer.Models.ArtistSongViewModel
<tr>
    <td>@Model.Song.ID</td>
    <td>@Model.Song.Name</td>
    <td>@Model.Song.Length</td>
    <td>
        <form method="post">
            <button asp-controller="Artist"  asp-action="UnlinkSongFromArtist" asp-route-artistId=@Model.Artist.ID asp-route-songId=@Model.Song.ID>Unlink artist from song</button>
        </form>
    </td>
</tr>

ASP/Views/Shared/MusicRowEdit.cshtml
@model PresentationLayer.Models.SongViewModel

<form asp-controller="Song" asp-action="EditMusic" method="post">
    <tr>
        <td>
            <input asp-for="ID" type="hidden" />
            <input asp-for="ID" type="number" disabled />
        </td>
        <td>
            <input asp-for="Name" type="text"/>
        </td>
        <td>
            <input asp-for="Length" type="number"/>
        </td>
        <td>
            <input type="submit" />
        </td>
    </tr>
</form>

ASP/Views/Shared/MusicRowSelect.cshtml
@model PresentationLayer.Models.SongViewModel
<tr>
    <td scope="row" class="checkbox_column">
        <input type="checkbox" name="musicCheckbox" value="@Model.ID"/>
    </td>
    <td>@Model.ID</td>
    <td>@Model.Name</td>
    <td>@Model.Length</td>
    <td>
        <a asp-controller="Song" asp-action="ListArtistsbySong" asp-route-songId="@Model.ID">
            <button>Bekijk artiesten</button>
        </a>
    </td>
</tr>

ASP/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ASP</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/ASP.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">ASP</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - ASP - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>